version: '3'
services:

# elasticsearch:
#  image: elasticsearch:alpine
#  environment:
#   - cluster.name=docker-cluster
#   - bootstrap.memory_lock=true
#   - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#  ulimits:
#   memlock:
#    soft: -1
#    hard: -1
#  ports:
#   - "9200:9200"
#   - "9300:9300"

 api:
   build:
     context: ./api
     args:
       app_env: ${APP_ENV}
   ports:
     - "8080:8080"
#  links:
#    - elasticsearch:elasticsearch
#   depends_on:
#    - elasticsearch
   volumes:
     - ./api:/go/src/github.com/PeterHenell/docker-compose-go-elastic-swagger/api

 swagger-server:
   image: quay.io/goswagger/swagger
   working_dir: /go/src/github.com/PeterHenell/docker-compose-go-elastic-swagger/api
   command: generate server -f /local/petstore.yaml -A myapp -t generated
   volumes:
     - ./api:/go/src/github.com/PeterHenell/docker-compose-go-elastic-swagger/api
     - ./swagger-spec:/local

 swagger-client:
   build: ./web/docker/swagger-client
   command: java -jar /swagger-codegen-cli.jar generate -l typescript-angular2 -i /local/petstore.yaml -o /output
   volumes:
     - ./web/app/client:/output
     - ./swagger-spec:/local
 web:
   build: ./web/docker/app
   command: serve
   ports:
    - "8000:8000"
   working_dir: /node
   volumes:
     - ./web/app:/node

#volumes:
#  shared:

